### ISSUE TITLE
PCB is ready

### ISSUE THREAD

**Issue by tkimva** [tkimva/fpga_trace_analyzer#30]
PCB Allegro PCB Si design software are ready in WCH 125 Lab. We can always access the lab.
In addition, I'm asking Tom if we can get software license which install our Laptop, so that we can work at home with our laptop. Will see.

In addition, I'll make some simple practice PCB board design for He Dai and Hui Li, who haven't any PCB design experiences. 

Thanks,
Taeyoung

**Comment by sheldonucr** [comment]
Taeyoung,

That is good to know. One more thing is that we need to learn the pcb design for high speed signals.  This is not easy tasks.

--Sheldon Tan


On Jan 23, 2015, at 2:54 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


PCB Allegro PCB Si design software are ready in WCH 125 Lab. We can always access the lab.
In addition, I'm asking Tom if we can get software license which install our Laptop, so that we can work at home with our laptop. Will see.

In addition, I'll make some simple practice PCB board design for He Dai and Hui Li, who haven't any PCB design experiences.

Thanks,
Taeyoung

-

**Comment by tkimva** [comment]
We know. We find the method as well as waiting the industry expert's help as you mentioned before. When can we see him?

**Comment by sheldonucr** [comment]
Yes. I will contact him soon.

--Sheldon


On Jan 23, 2015, at 5:49 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


We know. We find the method as well as waiting the industry expert's help as you mentioned before. When can we see him?

-

**Comment by tkimva** [comment]
Thank you, in the meantime, we will also study some basic and high speed methods too.
