### ISSUE TITLE
today's progress

### ISSUE THREAD

**Issue by Neutrogena** [tkimva/fpga_trace_analyzer#35]
1. worked with He, and tried communitcation with him, but the memory depth is too small. So we can only get some data, most of them are 0. 
2. I think it's better to have a meeting with you, do you have time tomorrow?

**Comment by tkimva** [comment]
I've been sick today so I couldn't go school and stayed at home, I'm not sure I can go tomorrow since I'm still having too much running nose with headache now. 

If I go school let's meet 2pm in the lab. However, it's better for you to avoid me since this cold is contagious.

If I cannot go school, then let's do Skype meeting, my Skype id is "taekim0", I'll keep you updated.
